transcription_task:
  description: |
    Transcribe the audio file located at {audio_path}.
    Ensure complete and accurate transcription of all spoken words.
    Capture the full dialogue including all questions and answers.
  expected_output: |
    A complete text transcript of the audio file with all spoken words captured accurately.
    The transcript should be clean and readable, preserving the natural flow of conversation.
  agent: "transcriptionist"

structuring_task:
  description: |
    Parse the transcript and structure it into a clear Question and Answer format.
    Identify and separate interviewer questions from candidate responses.
    Add a [TECHNICAL] tag before any question that requires technical knowledge or explanation.
    Examples of technical questions: algorithm explanations, system design, coding concepts, etc.
  expected_output: |
    A structured Q&A format document where:
    - Each interviewer question is clearly marked as "Interviewer: [question]"
    - Technical questions are marked as "Interviewer: [TECHNICAL] [question]"
    - Each candidate response is marked as "Candidate: [response]"
    - The dialogue flows naturally and is easy to follow
  agent: "dialogue_structurer"
  context_from: ["transcription_task"]

technical_analysis_task:
  description: |
    For every question tagged with [TECHNICAL]:
    1. First, evaluate the candidate's provided answer for accuracy and completeness
    2. Then, generate a detailed, comprehensive "ideal answer" as if writing for a textbook
    3. Include best practices, trade-offs, and real-world considerations
    4. Ensure the ideal answer is clear, well-structured, and educational
  expected_output: |
    A document containing for each technical question:
    - The original technical question
    - The candidate's answer
    - An evaluation of the candidate's answer (strengths and areas for improvement)
    - A comprehensive "Ideal Answer" section with the perfect response
  agent: "technical_architect"
  context_from: ["structuring_task"]

performance_review_task:
  description: |
    Create a comprehensive performance review by:
    1. Analyzing the candidate's technical answers against the ideal answers
    2. Evaluating behavioral question responses for structure (STAR method), clarity, and confidence
    3. Identifying overall strengths and areas for improvement
    4. Providing actionable feedback for interview performance improvement
  expected_output: |
    A complete performance review containing:
    - Overall Performance Summary (strengths and areas for improvement)
    - Technical Skills Assessment (comparison with ideal answers)
    - Communication Skills Assessment
    - Behavioral Response Analysis
    - Specific, actionable recommendations for improvement
  agent: "performance_analyst"
  context_from: ["structuring_task", "technical_analysis_task"]

quality_assurance_task:
  description: |
    Perform a final review of the entire interview analysis report.
    Check for:
    - Coherence and consistency throughout the document
    - Factual accuracy in technical content
    - Professional and constructive tone
    - Clear and actionable feedback
    - Proper formatting and organization
    Make any necessary edits to create a polished, professional final report.
  expected_output: |
    A polished, professional final report that includes:
    - All previous sections edited for quality and coherence
    - Consistent formatting throughout
    - Clear section headers and organization
    - Constructive and supportive tone
    - No errors or awkward phrasing
  agent: "quality_editor"
  context_from: ["performance_review_task", "structuring_task", "technical_analysis_task"]

export_task:
  description: |
    Take the final polished report and:
    1. Format it beautifully with proper markdown structure
    2. Add metadata (company: {company}, role: {role}, date: current date)
    3. Save to Notion database if credentials are available
    4. Otherwise, save as a well-formatted markdown file in the interviews directory
    5. Ensure all sections are properly organized with clear headers
  expected_output: |
    A confirmation message indicating:
    - Where the report was saved (Notion or local markdown file)
    - The filename or Notion page URL
    - Success status of the export operation
  agent: "notion_exporter"
  context_from: ["quality_assurance_task"]